- name: Install Apache web server
  yum: 
    name: '{{ item }}'
    state: installed
  with_items:
    - httpd
    - libselinux-python

- name: Set SELinux non-eforcing
  command: setenforce 0

- name: Change default apache vhost
  template: 
    src: default.tpl 
    dest: /etc/httpd/conf.d/000-default.conf

- name: Set global ServerName for apache config
  lineinfile: 
    dest: /etc/httpd/conf/httpd.conf 
    line: "ServerName localhost"

- name: Ensure Apache running
  service: 
    name: httpd 
    state: started 
    enabled: yes
