VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "wordpress-target-system"

    config.vm.network :private_network, ip: "192.168.50.20"

    config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 1024
        libvirt.cpus = 1
        libvirt.cpu_mode = 'host-passthrough'
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.sudo = true
    end

    config.vm.provision :shell, inline: "echo Good job! Now vagrant ssh"
end
