- name: MySql packages are installed
  yum: 
    name: '{{ item }}'
  with_items:
    - '{{ rhel6_package_name }}'
    - MySQL-python

- name: enable MySQL55 SCL
  shell: scl enable mysql55 bash
  args:
    creates: "/etc/init.d/mysql55-mysqld"

- name: Start the MySQL service
  service: 
    name: '{{ rhel6_service_name }}'
    state: started 
    enabled: yes
