- include: install-rhel6.yml
  when: 
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '6'

- include: install-rhel7.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'

- include: secure.yml
