- name: Set the root password for all root accounts
  mysql_user: 
    name: root 
    host: '{{ item }}'
    password: '{{ mysql_root_password }}'
    priv: '*.*:ALL,GRANT'
  with_items:
    - '{{ ansible_hostname }}'
    - 127.0.0.1
    - ::1
    - localhost
  when: ansible_hostname != 'localhost'

- name: Configure MySql for easy access as root user
  template: 
    src: .my.cnf.j2 
    dest: ~/.my.cnf 
    owner: root 
    group: root 
    mode: 0644

- name: ensure anonymous users are not in the database
  mysql_user: 
    name: '' 
    host: '*'
    state: absent

- name: Ensure firewalld is running
  service: 
    name: firewalld 
    state: running
  when: ansible_distribution_major_version == "7"

- name: Add allow rule for 3306 to firewall
  firewalld: 
    zone: public 
    port: 3306/tcp 
    permanent: true 
    state: enabled
  when: ansible_distribution_major_version == "7"

- name: Add allow rule for 3306 to firewall
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 3306
    jump: ACCEPT
  when: ansible_distribution_major_version == "6"

- name: remove the test database
  mysql_db: 
    name: test 
    state: absent
  notify:
    - Restart the MySQL service
