- name: Install Docker
  yum:
    name: docker
    state: latest

- name: Ensure Docker is enabled & running
  service: 
    name: docker 
    state: started 
    enabled: yes

- name: "SElinux: allow container to manage cgroups"
  seboolean:
    name: container_manage_cgroup
    persistent: yes
    state: yes
